### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by SebRut**

### CODE REVIEW

**Comment by twisterghost** [comment]
Awesome stuff. Ignore the failing build, I'm implementing travis and its angry at the moment. I'll merge this soon.

**Comment by twisterghost** [comment]
Would you mind squashing those commits down to one or two commits? Having 5 "update german.json" commits doesn't look fantastic in the commit history. Other than that, once this passes build, I'll merge it.

**Comment by SebRut** [comment]
"Squashing?"

**Comment by twisterghost** [comment]
http://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by twisterghost** [comment]
I can do it post-merge if you're not comfortable with that

**Pull request merged**
