### PR TITLE
basic dict testing added

### PR DESCRIPTION
**Pull request by SebRut**

### CODE REVIEW

**Comment by twisterghost** [comment]
I can take a look later today and see if I can help make this pass the build

**Comment by SebRut** [comment]
Problem is that chai expects a function inside the expect, but jshint refuses to accept functions in loop. I've re<d that you can also disable the function in loop check with "loopfunc".

**Comment by twisterghost** [comment]
The other option is to define the funciton outside of the loop, store it in a variable, and call it from within the loop. It is bad practice to define a function inside of a loop, but if you define it outside, its not an issue: 
```JavaScript
var testThing = function(thing) {
 // Do some stuff
}

for (var  i in whatever) {
  expect(testThing(i)).to.be.awesome;
}
```

**Comment by twisterghost** [comment]
Okay, so the error is stemming from the fact that it wants the thing you pass into expect to be a function, but you are calling the function inside of expect, which is returning an object, not a function.

Something like this should work:

```JavaScript
var generator = function(data) {
  return function() {
    JSON.parse(data);
  }
}

describe('dictionaries',function() {
  describe('#parseJSON',function() {
    it('should not throw an exception for any dictionary', function() {
      var dictFiles = fs.readdirSync('dict/');
      for(var f in dictFiles) {
          var file = path.join('dict/', dictFiles[f]);
          console.log('parsing file ' + file);
          var source = fs.readFileSync(file);
          var checkFunc = generator(source);
          expect(checkFunc).to.not.throw(Error);
        }
    });
  });
});
```

**Comment by twisterghost** [comment]
Just tried it myself - that seems to work. Once this is passing, I'll merge it in.

**Pull request merged**
